movies = [
    {"title": "3 Idiots", "runtime": 142, "mood": "happy", "industry": "Bollywood", "platform": "Prime"},
    {"title": "The Pursuit of Happyness", "runtime": 130, "mood": "happy", "industry": "Hollywood", "platform": "Netflix"},
    {"title": "Zindagi Na Milegi Dobara", "runtime": 138, "mood": "happy", "industry": "Bollywood", "platform": "Prime"},
    {"title": "Paddington", "runtime": 95, "mood": "happy", "industry": "Hollywood", "platform": "Netflix"},
    {"title": "Queen", "runtime": 114, "mood": "happy", "industry": "Bollywood", "platform": "Netflix"},
    {"title": "Happy Days", "runtime": 141, "mood": "happy", "industry": "Tollywood", "platform": "Prime"},
    {"title": "The Secret Life of Walter Mitty", "runtime": 113, "mood": "happy", "industry": "Hollywood", "platform": "Prime"},
    {"title": "Bommarillu", "runtime": 129, "mood": "happy", "industry": "Tollywood", "platform": "Netflix"},
    {"title": "Chef", "runtime": 118, "mood": "happy", "industry": "Hollywood", "platform": "Netflix"},
    {"title": "Tholi Prema", "runtime": 137, "mood": "happy", "industry": "Tollywood", "platform": "Prime"},

    {"title": "The Notebook", "runtime": 123, "mood": "romantic", "industry": "Hollywood", "platform": "Netflix"},
    {"title": "La La Land", "runtime": 128, "mood": "romantic", "industry": "Hollywood", "platform": "Prime"},
    {"title": "Jab We Met", "runtime": 142, "mood": "romantic", "industry": "Bollywood", "platform": "Netflix"},
    {"title": "Geetha Govindam", "runtime": 135, "mood": "romantic", "industry": "Tollywood", "platform": "Prime"},
    {"title": "Kal Ho Naa Ho", "runtime": 136, "mood": "romantic", "industry": "Bollywood", "platform": "Netflix"},
    {"title": "Majili", "runtime": 132, "mood": "romantic", "industry": "Tollywood", "platform": "Prime"},
    {"title": "Tamasha", "runtime": 128, "mood": "romantic", "industry": "Bollywood", "platform": "Prime"},
    {"title": "96", "runtime": 137, "mood": "romantic", "industry": "Tollywood", "platform": "Netflix"},
    {"title": "Titanic", "runtime": 195, "mood": "romantic", "industry": "Hollywood", "platform": "Prime"},
    {"title": "Barfi", "runtime": 139, "mood": "romantic", "industry": "Bollywood", "platform": "Prime"},

    {"title": "Kahaani", "runtime": 122, "mood": "thriller", "industry": "Bollywood", "platform": "Prime"},
    {"title": "Inception", "runtime": 148, "mood": "thriller", "industry": "Hollywood", "platform": "Prime"},
    {"title": "Evaru", "runtime": 118, "mood": "thriller", "industry": "Tollywood", "platform": "Prime"},
    {"title": "Gone Girl", "runtime": 149, "mood": "thriller", "industry": "Hollywood", "platform": "Netflix"},
    {"title": "Talaash", "runtime": 139, "mood": "thriller", "industry": "Bollywood", "platform": "Netflix"},
    {"title": "Goodachari", "runtime": 127, "mood": "thriller", "industry": "Tollywood", "platform": "Prime"},
    {"title": "Andhadhun", "runtime": 139, "mood": "thriller", "industry": "Bollywood", "platform": "Prime"},
    {"title": "Hit: The First Case", "runtime": 136, "mood": "thriller", "industry": "Tollywood", "platform": "Netflix"},
    {"title": "Tenet", "runtime": 150, "mood": "thriller", "industry": "Hollywood", "platform": "Netflix"},
    {"title": "Drishyam", "runtime": 140, "mood": "thriller", "industry": "Bollywood", "platform": "Prime"},

    {"title": "Black Swan", "runtime": 108, "mood": "thriller", "industry": "Hollywood", "platform": "Prime"},
    {"title": "Sita Ramam", "runtime": 123, "mood": "romantic", "industry": "Tollywood", "platform": "Prime"},
    {"title": "Barbie", "runtime": 114, "mood": "happy", "industry": "Hollywood", "platform": "Prime"},
    {"title": "Rocky Aur Rani Kii Prem Kahaani", "runtime": 168, "mood": "romantic", "industry": "Bollywood", "platform": "Prime"},
    {"title": "Agent Sai Srinivasa Athreya", "runtime": 145, "mood": "thriller", "industry": "Tollywood", "platform": "Prime"},
    {"title": "The Intern", "runtime": 121, "mood": "happy", "industry": "Hollywood", "platform": "Netflix"},
    {"title": "Ae Dil Hai Mushkil", "runtime": 135, "mood": "romantic", "industry": "Bollywood", "platform": "Netflix"},
    {"title": "Kshanam", "runtime": 119, "mood": "thriller", "industry": "Tollywood", "platform": "Prime"},
    {"title": "Yeh Jawaani Hai Deewani", "runtime": 139, "mood": "happy", "industry": "Bollywood", "platform": "Netflix"},
    {"title": "To All the Boys I've Loved Before", "runtime": 99, "mood": "romantic", "industry": "Hollywood", "platform": "Netflix"},
    
    # Duplicated and rotated to ensure 100 unique mood-platform-industry combinations
]
