movies = [
    {'title': 'Chhichhore', 'mood': 'thriller', 'runtime': 27, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Dangal', 'mood': 'romantic', 'runtime': 128, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Mersal', 'mood': 'happy', 'runtime': 63, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Pushpa', 'mood': 'happy', 'runtime': 35, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'The Family Man Ep1', 'mood': 'thriller', 'runtime': 62, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Baahubali', 'mood': 'thriller', 'runtime': 102, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Shershaah', 'mood': 'happy', 'runtime': 113, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Zindagi Na Milegi Dobara', 'mood': 'thriller', 'runtime': 98, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Tamasha', 'mood': 'happy', 'runtime': 57, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Gone Girl', 'mood': 'thriller', 'runtime': 172, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'PK', 'mood': 'romantic', 'runtime': 72, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Modern Love S01E01', 'mood': 'romantic', 'runtime': 117, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Brooklyn Nine-Nine S02E05', 'mood': 'romantic', 'runtime': 120, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Barfi', 'mood': 'romantic', 'runtime': 68, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Inception', 'mood': 'happy', 'runtime': 49, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Rockstar', 'mood': 'happy', 'runtime': 115, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'PK Part 2', 'mood': 'romantic', 'runtime': 35, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Jab We Met', 'mood': 'romantic', 'runtime': 50, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Paddington', 'mood': 'thriller', 'runtime': 150, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Stranger Things Ep1', 'mood': 'romantic', 'runtime': 50, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Rockstar Part 3', 'mood': 'thriller', 'runtime': 111, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Inception Part 1', 'mood': 'thriller', 'runtime': 149, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Yeh Jawaani Hai Deewani', 'mood': 'happy', 'runtime': 101, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Kantara', 'mood': 'happy', 'runtime': 74, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'The Big Sick', 'mood': 'romantic', 'runtime': 55, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Gone Girl Part 2', 'mood': 'romantic', 'runtime': 139, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'RRR', 'mood': 'romantic', 'runtime': 101, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Inception Part 1', 'mood': 'thriller', 'runtime': 178, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Raazi', 'mood': 'happy', 'runtime': 36, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Barfi Part 3', 'mood': 'happy', 'runtime': 48, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Breaking Bad S01E01', 'mood': 'romantic', 'runtime': 92, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Black Mirror S03E01', 'mood': 'romantic', 'runtime': 114, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Raazi Part 3', 'mood': 'happy', 'runtime': 84, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Koi Mil Gaya', 'mood': 'romantic', 'runtime': 151, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Breaking Bad S01E01 Part 2', 'mood': 'happy', 'runtime': 147, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Shershaah Part 3', 'mood': 'thriller', 'runtime': 125, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Kantara Part 1', 'mood': 'happy', 'runtime': 116, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Kantara Part 2', 'mood': 'happy', 'runtime': 121, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'The Good Place S01E01', 'mood': 'happy', 'runtime': 166, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'The Fault in Our Stars', 'mood': 'happy', 'runtime': 137, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Emily in Paris Ep1', 'mood': 'happy', 'runtime': 99, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Koi Mil Gaya Part 3', 'mood': 'romantic', 'runtime': 153, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Lagaan', 'mood': 'romantic', 'runtime': 145, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'The Family Man Ep1 Part 2', 'mood': 'thriller', 'runtime': 61, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'The Family Man Ep1 Part 3', 'mood': 'happy', 'runtime': 78, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Super Deluxe', 'mood': 'thriller', 'runtime': 155, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Barfi Part 2', 'mood': 'romantic', 'runtime': 30, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Barfi Part 3', 'mood': 'romantic', 'runtime': 31, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Breaking Bad S01E01 Part 1', 'mood': 'thriller', 'runtime': 55, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Emily in Paris Ep1 Part 2', 'mood': 'happy', 'runtime': 115, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Friends S01E01', 'mood': 'thriller', 'runtime': 141, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Baahubali Part 1', 'mood': 'romantic', 'runtime': 75, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Kapoor & Sons', 'mood': 'romantic', 'runtime': 102, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'The Pursuit of Happyness', 'mood': 'happy', 'runtime': 164, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'The Notebook', 'mood': 'romantic', 'runtime': 99, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': '3 Idiots', 'mood': 'happy', 'runtime': 53, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Friends S01E01 Part 3', 'mood': 'thriller', 'runtime': 37, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Lagaan Part 1', 'mood': 'romantic', 'runtime': 24, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'How I Met Your Mother S01E01', 'mood': 'happy', 'runtime': 170, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Mersal Part 3', 'mood': 'thriller', 'runtime': 38, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Kantara Part 1', 'mood': 'happy', 'runtime': 97, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Kantara Part 2', 'mood': 'romantic', 'runtime': 77, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Dil Dhadakne Do', 'mood': 'happy', 'runtime': 155, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Paddington Part 1', 'mood': 'happy', 'runtime': 135, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Breaking Bad S01E01 Part 2', 'mood': 'happy', 'runtime': 114, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Friends S01E01 Part 3', 'mood': 'happy', 'runtime': 138, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Paddington Part 1', 'mood': 'thriller', 'runtime': 60, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Barfi Part 2', 'mood': 'happy', 'runtime': 31, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Mersal Part 3', 'mood': 'thriller', 'runtime': 72, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Koi Mil Gaya Part 1', 'mood': 'happy', 'runtime': 60, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Pushpa Part 2', 'mood': 'happy', 'runtime': 135, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'House of Secrets Ep1', 'mood': 'romantic', 'runtime': 160, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Mersal Part 1', 'mood': 'thriller', 'runtime': 106, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'The Good Place S01E01 Part 2', 'mood': 'thriller', 'runtime': 152, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Emily in Paris Ep1 Part 3', 'mood': 'thriller', 'runtime': 24, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Tamasha Part 1', 'mood': 'thriller', 'runtime': 167, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'The Notebook Part 2', 'mood': 'thriller', 'runtime': 68, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Barfi Part 3', 'mood': 'thriller', 'runtime': 59, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'The Fault in Our Stars Part 1', 'mood': 'romantic', 'runtime': 69, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Breaking Bad S01E01 Part 2', 'mood': 'happy', 'runtime': 158, 'platform': 'Prime', 'industry': 'Tollywood'},
    {'title': 'Kapoor & Sons Part 3', 'mood': 'romantic', 'runtime': 106, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Tamasha Part 1', 'mood': 'happy', 'runtime': 173, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'The Family Man Ep1 Part 2', 'mood': 'happy', 'runtime': 125, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Emily in Paris Ep1 Part 3', 'mood': 'happy', 'runtime': 20, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Paddington Part 1', 'mood': 'romantic', 'runtime': 130, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'PK Part 2', 'mood': 'thriller', 'runtime': 85, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Black Mirror S03E01 Part 3', 'mood': 'romantic', 'runtime': 176, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'The Good Place S01E01 Part 1', 'mood': 'thriller', 'runtime': 59, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'The Fault in Our Stars Part 2', 'mood': 'happy', 'runtime': 42, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Brooklyn Nine-Nine S02E05 Part 3', 'mood': 'happy', 'runtime': 55, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': 'Chhichhore Part 1', 'mood': 'thriller', 'runtime': 114, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Kapoor & Sons Part 2', 'mood': 'happy', 'runtime': 43, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'Shershaah Part 3', 'mood': 'thriller', 'runtime': 172, 'platform': 'Prime', 'industry': 'Bollywood'},
    {'title': 'Kapoor & Sons Part 1', 'mood': 'thriller', 'runtime': 53, 'platform': 'Prime', 'industry': 'Hollywood'},
    {'title': '3 Idiots Part 2', 'mood': 'happy', 'runtime': 180, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Student of the Year', 'mood': 'thriller', 'runtime': 130, 'platform': 'Netflix', 'industry': 'Tollywood'},
    {'title': 'The Pursuit of Happyness Part 1', 'mood': 'thriller', 'runtime': 67, 'platform': 'Netflix', 'industry': 'Bollywood'},
    {'title': 'Emily in Paris Ep1 Part 2', 'mood': 'thriller', 'runtime': 30, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': '10 Things I Hate About You', 'mood': 'thriller', 'runtime': 66, 'platform': 'Netflix', 'industry': 'Hollywood'},
    {'title': 'Breaking Bad S01E01 Part 1', 'mood': 'thriller', 'runtime': 89, 'platform': 'Netflix', 'industry': 'Bollywood'},
]